#开发环境配置
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_demo
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.hackcrown.demo.domain

login-intercepter-switch: off

login-filter-switch: off

